[package]
name = "plactice_imageproc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
imageproc = "0.23.0"
slint = "1.3.2"
clipboard = "0.5.0"
anyhow = "1.0.79"
